# Project Milestone 1 - Deaths in NYC

This projects aims to analyze and discuss New York City Leading Causes of Death dataset from NYC data found here:
https://data.cityofnewyork.us/Health/New-York-City-Leading-Causes-of-Death/jb7j-dtam/about_data

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.formula.api as smf
import seaborn as sns
import numpy as np
 
%matplotlib inline

In [13]:
Nyc_Deaths_filter = pd.read_csv("New_York_City_Leading_Causes_of_Death.csv", na_values = ["-","."])
Nyc_Deaths = Nyc_Deaths_filter.dropna()
Nyc_Deaths

,Year,Leading Cause,Sex,Race Ethnicity,Deaths,Death Rate,Age Adjusted Death Rate
0,2011,"Nephritis, Nephrotic Syndrome and Nephrisis (N...",F,Black Non-Hispanic,83.0,7.9,6.9
1,2009,Human Immunodeficiency Virus Disease (HIV: B20...,F,Hispanic,96.0,8.0,8.1
2,2009,Chronic Lower Respiratory Diseases (J40-J47),F,Hispanic,155.0,12.9,16.0
3,2008,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",F,Hispanic,1445.0,122.3,160.7
4,2009,Alzheimer's Disease (G30),F,Asian and Pacific Islander,14.0,2.5,3.6
...,...,...,...,...,...,...,...
1088,2010,"Intentional Self-Harm (Suicide: X60-X84, Y87.0)",M,Asian and Pacific Islander,46.0,8.8,8.7
1089,2013,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",M,Black Non-Hispanic,1868.0,217.7,258.5
1090,2008,Diabetes Mellitus (E10-E14),M,Hispanic,191.0,17.3,31.3
1092,2008,Chronic Lower Respiratory Diseases (J40-J47),M,Asian and Pacific Islander,46.0,9.2,16.1
1093,2008,"Accidents Except Drug Posioning (V01-X39, X43,...",M,Asian and Pacific Islander,53.0,10.6,12.2

This data set has been filtered to remove missing data marked as ".", using the dropna parameter.

              Year
count  1094.000000
mean   2010.477148
std       2.293419
min    2007.000000
25%    2008.000000
50%    2010.000000
75%    2012.000000
max    2014.000000